### PR TITLE
Bump to 0.8.11

### PR DESCRIPTION
**Pull request by mariusvniekerk**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@mariusvniekerk do you want to add yourself as a maintainer too?

**Comment by mariusvniekerk** [comment]
@ocefpaf i did :D

**Comment by ocefpaf** [comment]
> @ocefpaf i did :D

Awesome! Any idea what is happening with Windows?

**Comment by mariusvniekerk** [comment]
not sure, it might be related to some of the console overrides that irkernel does?  kinda weird

**Comment by mariusvniekerk** [comment]
@bgruening @johanneskoester Any hints on how to get this thing building on windows?

**Comment by bgruening** [comment]
@mariusvniekerk https://github.com/conda-forge/r-base-feedstock/issues/26
But you have found it already :)

**Comment by mariusvniekerk** [comment]
@ocefpaf passing now!

**Comment by mariusvniekerk** [comment]
@ocefpaf seems this is just appveyor not sending the completion signal to gh.  Safe to merge now

**Review by jdblischak — APPROVED** [review]

**Comment by mariusvniekerk** [comment]
@jakirkham can I get a merge here, please? thanks

**Comment by ocefpaf** [comment]
What happened with appveyor?

**Comment by jdblischak** [comment]
@ocefpaf I've had this happen once before. I don't know what it is causing it. The Appveyor builds complete successfully, but this update never makes it back to GitHub.

https://github.com/conda-forge/r-agricolae-feedstock/pull/3#issuecomment-341927324

**Comment by jakirkham** [comment]
Checked the webhook status. The issue is rate limiting, which has already been raised with AppVeyor ( https://github.com/appveyor/ci/issues/1045 ).

**Pull request merged**
