### PR TITLE
Update irkernel to 0.8.15

### PR DESCRIPTION
**Pull request by philip-khor**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by philip-khor** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
Hm, merged... but does not build.

**Comment by dpryan79** [comment]
Looks like there was a new conda version 35 minutes ago and they changed the `conda clean` syntax.

**Comment by dpryan79** [comment]
Actually, the `--lock` option is simply broken.

**Comment by dbast** [comment]
Ok, lets wait a bit to after the migration issues are solved... will retrigger master in 12-24h according the status in gitter

**Comment by dbast** [comment]
Solved via https://github.com/conda-forge/r-irkernel-feedstock/pull/13

**Pull request merged**
